### ISSUE TITLE
set up web hooks on readthedocs

### ISSUE THREAD

**Issue by pyenergyplus** [pyenergyplus/witheppy#49]
So the documentation is updated automatically.

**Comment by pyenergyplus** [comment]
see
https://docs.readthedocs.io/en/stable/integrations.html#github

**Comment by santoshphilip** [comment]
set up an automation for tags
https://readthedocs.org/dashboard/witheppy/rules/

**Comment by santoshphilip** [comment]
not sure if all of this is working as needed.
Closing for now.
